root = "."
tmp_dir = "tmp"

[build]
  cmd = "make generate && go build -o ./tmp/main ./cmd/server"
  entrypoint = ["./tmp/main"]
  delay = 500
  exclude_dir = ["tmp", "bin", "cache"]
  exclude_regex = ["_templ\\.go$", "internal/db/.*\\.go$"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "templ", "sql"]
  include_dir = []
  kill_delay = "2s"
  send_interrupt = true
  stop_on_error = false

[log]
  main_only = true
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
